import { PAL, type PaletteKey } from "./palette";

export type Legend = Record<string, PaletteKey | "none">;

export interface SpriteDef {
  /** Rows of equal-length strings; each char maps through `legend`. '.' is always transparent. */
  rows: string[];
  legend: Legend;
}

const bitmapCache = new Map<string, HTMLCanvasElement>();

/** Render a hand-authored pixel-grid sprite to a cached offscreen canvas (1 art-pixel = 1 canvas px). */
export function getSpriteBitmap(key: string, def: SpriteDef): HTMLCanvasElement {
  const cached = bitmapCache.get(key);
  if (cached) return cached;

  const h = def.rows.length;
  const w = Math.max(...def.rows.map((r) => r.length));
  const canvas = document.createElement("canvas");
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext("2d")!;
  ctx.imageSmoothingEnabled = false;

  for (let y = 0; y < h; y++) {
    const row = def.rows[y];
    for (let x = 0; x < w; x++) {
      const ch = row[x] ?? ".";
      if (ch === "." || ch === " ") continue;
      const paletteKey = def.legend[ch];
      if (!paletteKey || paletteKey === "none") continue;
      ctx.fillStyle = PAL[paletteKey];
      ctx.fillRect(x, y, 1, 1);
    }
  }

  bitmapCache.set(key, canvas);
  return canvas;
}

/** Build a cache key that also captures a variant/frame index. */
export function spriteKey(name: string, variant: number | string = 0): string {
  return `${name}#${variant}`;
}

/** Register + fetch a bitmap generated by an arbitrary draw function (for procedural tiles). */
export function getProceduralBitmap(
  key: string,
  size: { w: number; h: number },
  draw: (ctx: CanvasRenderingContext2D) => void,
): HTMLCanvasElement {
  const cached = bitmapCache.get(key);
  if (cached) return cached;
  const canvas = document.createElement("canvas");
  canvas.width = size.w;
  canvas.height = size.h;
  const ctx = canvas.getContext("2d")!;
  ctx.imageSmoothingEnabled = false;
  draw(ctx);
  bitmapCache.set(key, canvas);
  return canvas;
}

function hexToRgb(hex: string) {
  const h = hex.replace("#", "");
  return {
    r: parseInt(h.slice(0, 2), 16),
    g: parseInt(h.slice(2, 4), 16),
    b: parseInt(h.slice(4, 6), 16),
  };
}

const outlineCache = new WeakMap<HTMLCanvasElement, HTMLCanvasElement>();

/**
 * Wraps a sprite in a 1px dark rim so it separates from the terrain behind it.
 * Only near-opaque pixels seed the outline, so baked-in soft contact shadows
 * don't get rimmed. Results are cached per source bitmap.
 */
export function outlineBitmap(src: HTMLCanvasElement, color = "#1b1410", solidAlpha = 200): HTMLCanvasElement {
  const cached = outlineCache.get(src);
  if (cached) return cached;

  const w = src.width + 2;
  const h = src.height + 2;
  const out = document.createElement("canvas");
  out.width = w;
  out.height = h;
  const ctx = out.getContext("2d")!;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(src, 1, 1);

  const img = ctx.getImageData(0, 0, w, h);
  const d = img.data;
  const alphaAt = (x: number, y: number) => (x < 0 || y < 0 || x >= w || y >= h ? 0 : d[(y * w + x) * 4 + 3]);
  const { r, g, b } = hexToRgb(color);

  const targets: number[] = [];
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const i = (y * w + x) * 4;
      if (d[i + 3] >= solidAlpha) continue;
      if (
        alphaAt(x - 1, y) >= solidAlpha ||
        alphaAt(x + 1, y) >= solidAlpha ||
        alphaAt(x, y - 1) >= solidAlpha ||
        alphaAt(x, y + 1) >= solidAlpha
      ) {
        targets.push(i);
      }
    }
  }
  for (const i of targets) {
    d[i] = r;
    d[i + 1] = g;
    d[i + 2] = b;
    d[i + 3] = 255;
  }
  ctx.putImageData(img, 0, 0);
  outlineCache.set(src, out);
  return out;
}

/** Wraps a bitmap-producing function so every frame it returns comes back outlined. */
export function outlined(fn: (time: number) => HTMLCanvasElement): (time: number) => HTMLCanvasElement {
  return (time: number) => outlineBitmap(fn(time));
}

/** Deterministic pseudo-random in [0,1) from integer coords — stable "designed noise", not Math.random. */
export function hashNoise(x: number, y: number, seed = 0): number {
  let h = x * 374761393 + y * 668265263 + seed * 2246822519;
  h = (h ^ (h >>> 13)) * 1274126177;
  h = h ^ (h >>> 16);
  return ((h >>> 0) % 1000) / 1000;
}
